ScrollReveal().reveal("#projectOne", { reset: true, delay: 1000, easing: "ease-in-out" })
ScrollReveal().reveal("#projectTwo", { reset: true, delay: 1000, easing: "ease-in-out" })
ScrollReveal().reveal("#projectThree", { reset: true, delay: 1000, easing: "ease-in-out" })
ScrollReveal().reveal("#projectFour", { reset: true, delay: 1000, easing: "ease-in-out" })
ScrollReveal().reveal("#projectFive", { reset: true, delay: 1000, easing: "ease-in-out" })